backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'coins'
    label: 'Coin'
    folder: 'coins'
    create: true
    slug: 'coin'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true, default: "Bitcoin" }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY" }
      - { label: 'Symbol', name: 'symbol', widget: 'string', required: true, default: "BTC" }
      - { label: 'Network Type', name: 'network', widget: 'string', required: true, default: "Testnet" }
      - { label: 'Docs', name: 'docs', widget: 'string', required: true, default: "https://wiki.veriblock.org/index.php/HowTo_PoP_vBTC" }
      - { label: 'GitHub', name: 'github', widget: 'string', required: true, default: "http://github.com/bitcoin/bitcoin" }
      - { label: 'Altchain ID', name: 'altchainid', widget: 'number', required: true, default: 1337, min: 0, max: 18446744073709551615, value_type: int}
      - { label: 'Version', name: 'version', widget: 'string', required: true, default: "1.0.0" }
      - { label: 'Artifacts', name: 'artifacts', widget: 'string', required: true, default: "https://github.com/bitcoin/bitcoin/archive/v0.21.0.zip" }
      - { label: 'Sample Node config', name: 'config', widget: 'markdown', required: false }
      - { label: 'Compatible APM artifact', name: 'apm-artifact', widget: 'string', required: true, default: "https://github.com/bitcoin/bitcoin/archive/v0.21.0.zip" }
      - { label: 'Sample APM config', name: 'apmconfig', widget: 'markdown', required: false }
